### ISSUE TITLE
Panic accessing default audio device on Debian Linux

### ISSUE THREAD

**Issue by hallettj** [xasopheno/WereSoCool#473]
I'm not able to run the server due to a panic that appears to involve unwrapping something to access the default audio device. I'm running Debian Testing with Gnome 3.38. Here is the trace:

```
WereSoCool on  makefile-changes via 𝗥 v1.46.0 took 6m 34s
[I] ✘130 ❯ export RUST_BACKTRACE=full

WereSoCool on  makefile-changes via 𝗥 v1.46.0
[I] ❯ make dev
(cd application && yarn build-backend && yarn dev)
yarn run v1.22.4
$ cd server && ./build_static.sh && cd ../ && cp ../target/release/weresocool_server extraResources/weresocool_server
LINUX...will NOT build built statically.
    Finished release [optimized] target(s) in 0.42s
Done in 0.56s.
yarn run v1.22.4
$ yarn build-backend && cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cd server && ./build_static.sh && cd ../ && cp ../target/release/weresocool_server extraResources/weresocool_server
LINUX...will NOT build built statically.
    Finished release [optimized] target(s) in 0.12s
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1601763051501-0.9033573657357188/node but npm is using /home/jesse/.nvm/versions/node/v14.8.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> weresocool@1.0.16 start-main-dev /home/jesse/projects/rust/WereSoCool/application
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts

18:10:54.375 › App starting...
(node:1085911) UnhandledPromiseRejectionWarning: Error: Loading extension at /home/jesse/projects/rust/WereSoCool/application/node_modules/devtron failed with: The 'manifest_version' key must be present and set to 2 (without quotes). See developer.chrome.com/extensions/manifestVersion.html for details.
(node:1085911) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1085911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1085911) ExtensionLoadWarning: Warnings loading extension at /home/jesse/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
Listening on 4588
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/portaudio-0.7.0/src/lib.rs:250:60
stack backtrace:
   0:     0x56245cd904e5 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x56245cd904e5 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x56245cd904e5 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x56245cd904e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x56245cdb77dc - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x56245cd8a3b2 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x56245cd92b50 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56245cd92b50 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56245cd92b50 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x56245cd9289c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x56245cd93193 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x56245cd92d8b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x56245cdb5741 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  13:     0x56245cdb568d - core::panicking::panic::h7ece43057e5422d4
                               at src/libcore/panicking.rs:50
  14:     0x56245cbbbfbb - portaudio::PortAudio::default_output_device::h108773ff6f4cc58f
  15:     0x56245cb308f9 - weresocool::portaudio::real_time_render_manager::real_time_render_manager::h2bcc0cfc5ef3c050
  16:     0x56245caa979e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcfc3be826150f1ab
  17:     0x56245caf772b - std::thread::local::LocalKey<T>::with::ha3d26d72f727b90c
  18:     0x56245ca71a00 - tokio::macros::scoped_tls::ScopedKey<T>::set::h662ee624253722e9
  19:     0x56245caa90ad - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haf6e7e005092049a
  20:     0x56245caf764b - std::thread::local::LocalKey<T>::with::hcf2bf56aa9969295
  21:     0x56245ca70e2a - tokio::macros::scoped_tls::ScopedKey<T>::set::h21b9050f33f67431
  22:     0x56245caa2f94 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::haa3a68f9ef8bf00d
  23:     0x56245caedf71 - tokio::runtime::context::enter::h2565055bab1ac0f8
  24:     0x56245cabcfde - tokio::runtime::handle::Handle::enter::h0969bfb2c129dbd4
  25:     0x56245cad2567 - weresocool_server::main::h3611dd802127c0ae
  26:     0x56245cae44a3 - std::rt::lang_start::{{closure}}::h865a623185261596
  27:     0x56245cd93633 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  28:     0x56245cd93633 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  29:     0x56245cd93633 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  30:     0x56245cd93633 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  31:     0x56245cd93633 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  32:     0x56245cad2602 - main
  33:     0x7fe94eecbcca - __libc_start_main
  34:     0x56245ca5e3fa - _start
  35:                0x0 - <unknown>
Panic in Arbiter thread.
```

**Comment by xasopheno** [comment]
Strange. Took a look. I've tried starting from scratch on my machine, but
it's still working so I haven't been able to reproduce it on my end. It
looks like it's failing in the rust portaudio package. Happy to chat this
week and see if we can get it running.

Sorry it's been a challenge. My linux foo is not terribly good - this arch
machine is my first - so I'm sure I've missed something important. Hope
you're having a great weekend.

D

**Comment by hallettj** [comment]
I fixed it! The server worked after I installed `portaudio19-dev` and did a clean compile. I saw a note in the Portaudio bindings crate documentation that it downloads its own copy of the Portaudio library if it's not installed. I think it downloaded a version of Portaudio that is not compatible with my system. But installing the dev library from the Debian repo works.
